# Generated by Django 3.0.2 on 2020-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0002_auto_20200117_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='mob_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='post_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
