# Generated by Django 3.0.2 on 2020-01-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0003_auto_20200117_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fuel', models.CharField(max_length=15)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transmission', models.CharField(max_length=15)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_model', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Category4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_car', models.CharField(max_length=15)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Car_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHub.Category4'),
        ),
        migrations.AddField(
            model_name='car',
            name='Fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHub.Category1'),
        ),
        migrations.AddField(
            model_name='car',
            name='Transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHub.Category2'),
        ),
        migrations.AddField(
            model_name='car',
            name='Year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHub.Category3'),
        ),
    ]
