# Generated by Django 3.0.2 on 2020-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0004_auto_20200117_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='cover1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='cover2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
