# Generated by Django 3.0.2 on 2020-01-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0006_auto_20200124_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='country',
        ),
    ]
