# Generated by Django 3.0.2 on 2020-01-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0007_remove_manufacturer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoHub.Category5'),
        ),
    ]
