# Generated by Django 3.0.2 on 2020-01-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHub', '0009_category5_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category5',
            name='desc',
        ),
    ]
